# Generated by Django 3.2 on 2021-07-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField(max_length=250)),
                ('notification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.URLField(max_length=255)),
                ('created_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_timestamp', models.DateTimeField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='message.notification')),
                ('orguser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='user.orguser')),
                ('received_by_user_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
